version: "3.8"

services:
  # Service untuk aplikasi Go
  app:
    build: .
    container_name: project-akhir-exam
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=project_akhir_exam
    depends_on:
      - mysql

  # Service untuk MySQL
  mysql:
    image: mysql:8
    # container_name: containerproject_akhir_exam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project_akhir_exam
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
